language: go

go:
  - 1.7beta2

install:
  - go get -u golang.org/x/tools/cmd/goimports

script:
  - go get -d -t ./...
  - go test ./...
  - >
    goimports -d -e ./ | grep '.*' && { echo; echo "Aborting due to non-empty goimports output."; exit 1; } || :
